quarkus.application.name=inventory-service
quarkus.http.port=8081
quarkus.http.host=0.0.0.0
quarkus.shutdown.timeout=30S

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094,localhost:9096}
quarkus.kafka.health.enabled=true
mp.messaging.connector.smallrye-kafka.bootstrap.servers=${kafka.bootstrap.servers}
mp.messaging.connector.smallrye-kafka.health-enabled=true
mp.messaging.connector.smallrye-kafka.health-readiness-enabled=true
mp.messaging.connector.smallrye-kafka.health-readiness-timeout=5000
mp.messaging.connector.smallrye-kafka.acks=all
mp.messaging.connector.smallrye-kafka.enable.idempotence=true

quarkus.smallrye-health.root-path=/q/health
quarkus.smallrye-openapi.path=/q/openapi
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.http.non-application-root-path=/q

%prod.quarkus.log.console.json.enabled=true
%prod.quarkus.log.console.json.pretty=false
%dev.quarkus.log.console.json.enabled=true
%dev.quarkus.log.console.json.pretty=true
%test.quarkus.log.console.json.enabled=false

quarkus.kafka.devservices.enabled=true
%prod.quarkus.kafka.devservices.enabled=false
